# Generated by Django 3.1.2 on 2020-11-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bus',
            fields=[
                ('routeId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('locationNo', models.CharField(default='3', max_length=5)),
                ('lowPlate', models.CharField(default='0', max_length=3)),
                ('plateNo', models.CharField(default='경기70바5703', max_length=15)),
                ('predictTime', models.CharField(default='4', max_length=5)),
                ('remainSeatCnt', models.CharField(default='25', max_length=3)),
                ('staOrder', models.CharField(default='50', max_length=5)),
                ('stationId', models.CharField(default='203000165', max_length=10)),
            ],
            options={
                'ordering': ['routeId'],
            },
        ),
    ]
