# Generated by Django 3.1.2 on 2020-11-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='버스번호',
            field=models.CharField(default='4', max_length=5),
        ),
    ]
