# Generated by Django 3.1.2 on 2020-11-06 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businfo', '0002_bus_버스번호'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='plateNo',
            new_name='번호판',
        ),
        migrations.RenameField(
            model_name='bus',
            old_name='locationNo',
            new_name='현재위치',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='lowPlate',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='predictTime',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='remainSeatCnt',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='staOrder',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='stationId',
        ),
    ]
